# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.IntegerField()),
                ('day', models.CharField(max_length=9)),
                ('startingTime', models.TimeField()),
                ('endingTime', models.TimeField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('place', models.CharField(max_length=250)),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instanceId', models.IntegerField(default=0)),
                ('day', models.CharField(max_length=9)),
                ('startingTime', models.TimeField()),
                ('duration', models.TimeField()),
                ('canMove', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
