# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 11:49
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taskmanager', '0002_auto_20170724_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
            ],
        ),
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Day'),
        ),
        migrations.AlterField(
            model_name='weeklyschedule',
            name='day',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='taskmanager.Day'),
        ),
    ]
